baseURL = "/"
languageCode = "en"
contentDir = "content"
enableEmoji = true
enableGitInfo = true
sectionPagesMenu = "main"
defaultContentLanguage = 'en'
[languages]
[languages.en]
title = "Prusa Custom Firmware"
languageName = "English"
weight = 10
# [languages.fr]
# title = "Lotus Docs Exemple de Site"
# languageName = "FranÃ§ais"
# contentDir = "content/fr"
# weight = 20
# [languages.de]
# title = "Lotus Docs Beispiel Site"
# languageName = "Deutsch"
# contentDir = "content/de"
# weight = 30

[module]
# uncomment line below for temporary local development of module
# or when using a 'theme' as a git submodule
replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
[[module.imports]]
path = "github.com/colinwilson/lotusdocs"
disable = false
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[markup]
defaultMarkdownHandler = "goldmark"
[markup.tableOfContents]
endLevel = 3
startLevel = 1
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
# [markup.highlight]
#   codeFences = false # disables Hugo's default syntax highlighting
# [markup.goldmark.parser]
#   [markup.goldmark.parser.attribute]
#     block = true
#     title = true

[params]

google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
]

sans_serif_font = "Inter"     # Default is System font
secondary_font  = "Inter"     # Default is System font
mono_font       = "Fira Code" # Default is System font

[params.footer]
copyright = ""
# version = true # includes git commit info

[params.social]
codeberg = "ellafoxo/Prusa-Custom-Firmware"
# github = "ellafoxo"
# github = ""        # YOUR_GITHUB_ID or YOUR_GITHUB_URL
# twitter = ""       # YOUR_TWITTER_ID
# instagram = "colinwilson"     # YOUR_INSTAGRAM_ID
# rss = true                    # show rss icon with link

[params.docs] # Parameters for the /docs 'template'
title           = "Prusa Custom Firmware"           # default html title for documentation pages/sections

pathName        = ""                            # path name for documentation site | default "docs"

themeColor      = "orange"                            # (optional) - Set theme accent colour. Options include: blue (default), orange, green, red, yellow, emerald, cardinal, magenta, cyan

darkMode        = false                                # enable dark mode option? default false

prism           = true                                # enable syntax highlighting via Prism

prismTheme      = "lucario"                           # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

# gitinfo
repoURL         = "codeberg.org/ellafoxo/Prusa-Custom-Firmware"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
repoBranch      = "main"
editPage        = false                               # enable 'Edit this page' feature - default false
lastMod         = true                                # enable 'Last modified' date on pages - default false
lastModRelative = true                                # format 'Last modified' time as relative - default true

sidebarIcons    = true                                # enable sidebar icons? default false
breadcrumbs     = true                                # default is true
backToTop       = true                                # enable back-to-top button? default true

# ToC
toc             = true                                # enable table of contents? default is true
tocMobile       = true                                # enable table of contents in mobile view? default is true
scrollSpy       = false                                # enable scrollspy on ToC? default is true

# front matter
descriptions    = false                                # enable front matter descriptions under content title?
titleIcon       = false                                # enable front matter icon title prefix? default is false

# content navigation
navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description

# Link behaviour
intLinkTooltip  = true                                # Enable a tooltip for internal links that displays info about the destination? default false
# extLinkNewTab   = false                             # Open external links in a new Tab? default true
# logoLinkURL = ""                                    # Set a custom URL destination for the top header logo link.

[params.flexsearch] # Parameters for FlexSearch
enabled             = false
# tokenize            = "full"
# optimize            = true
# cache               = 100
# minQueryChar        = 3 # default is 0 (disabled)
# maxResult           = 5 # default is 5
# searchSectionsIndex = []

[params.docsearch] # Parameters for DocSearch
# appID     = "" # Algolia Application ID
# apiKey    = "" # Algolia Search-Only API (Public) Key
# indexName = "" # Index Name to perform search on (or set env variable HUGO_PARAM_DOCSEARCH_indexName)

# [[menu.primary]]
#     name  = "Showcase"
#     url = "/showcase"
#     identifier = "showcase"
#     weight = 20

# [[menu.primary]]
#     name  = "Community"
#     url = "https://github.com/colinwilson/lotusdocs/discussions"
#     identifier = "community"
#     weight = 30
